on:
  push:
    branches:
      - main
      - test
name: Release provider
jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          sed -i 's/version \= \"local-build\"/version = \"${{ env.release_tag }}\"/' main.go
          mkdir bin
          go build -ldflags="-s -w" -o bin/device-provider
          zip -j device-provider.zip bin/device-provider
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: device-provider.zip
          asset_name: device-provider.zip
          tag: Latest
          overwrite: true
