on:
  push:
    branches:
      - main
      - test
    tags:
      - 'v*'
name: Release provider
jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Get the tag version
        id: tag
        run: echo ::set-output name=TAG_VERSION::${GITHUB_REF#refs/tags/}
      - name: Test
        run: echo ${{ steps.get_version.outputs.TAG_VERSION }}
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          sed -i 's/version \= \"local-build\"/version = \"${{ env.release_tag }}\"/' main.go
          mkdir bin
          go build -ldflags="-s -w" -o bin/device-provider
          zip -j device-provider.zip bin/device-provider
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: device-provider.zip
          asset_name: device-provider.zip
          tag: ${{ steps.get_version.outputs.TAG_VERSION }}
          overwrite: true
